services:
  - type: web
    name: xyd-js-docs
    env: static
    buildCommand: bunx @xyd-js/cli build
    staticPublishPath: .xyd/build/client 
    bunVersion: 1.1.0
    routes:
      - type: rewrite
        source: /
        destination: /introduction/
      - type: rewrite
        source: /index.html
        destination: /introduction/
