services:
  - type: web
    name: xyd-js-docs
    env: static
    buildCommand: |
      npm install -g bun
      bunx @xyd-js/cli build
    staticPublishPath: .xyd/build/client 
    routes:
      - type: rewrite
        source: /
        destination: /introduction/
      - type: rewrite
        source: /index.html
        destination: /introduction/
