services:
  - type: web
    name: xyd-js-docs
    env: static
    buildCommand: bun x xyd build
    staticPublishPath: .xyd/build/client 
    envVars:
      - key: BUN_VERSION
        value: 1.1.0
    routes:
      - type: rewrite
        source: /
        destination: /introduction/
      - type: rewrite
        source: /index.html
        destination: /introduction/
